In [59]:
import numpy as np

In [2]:
np.ones((10,9)) * 5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [8]:
arr[:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
slice_of_arr = arr[0:6]

In [13]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:] = 99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_copy = arr.copy()

In [18]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy[:6] = np.arange(0,6)

In [20]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [23]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr_2d[1,2]

6

In [25]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

#Fancy Indexing

In [26]:
#Set up matrix
arr2d = np.zeros((10,10))

In [27]:
#Length of array
arr_length = arr2d.shape[1]

In [28]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
arr2d    

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [29]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [30]:
arr_2d_d = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [31]:
arr_2d_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr_2d_d_length = arr_2d_d.shape[1]

In [36]:
arr_2d_d_length

3

In [39]:
for i in range(arr_2d_d_length):
    arr_2d_d[i] = i
arr_2d_d

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [50]:
arr_2d_d[[2,0,1]]

array([[2, 2, 2],
       [0, 0, 0],
       [1, 1, 1]])

In [86]:
arr = np.arange(0,11)

In [87]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [88]:
arr.argmax()

10

In [89]:
arr.argmin()

0

In [90]:
arr.min()

0

In [91]:
arr.max()

10

In [92]:
bool_arr = arr > 4

In [93]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [94]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [95]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])