In [4]:
from __future__ import absolute_import, division, print_function, unicode_literals


import tensorflow as tf

In [17]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [18]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [19]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[ 0.0077027 ,  0.5813673 , -0.7309927 ,  0.12109216,  0.5905458 ,
         0.03595192, -0.27973986, -0.3867794 , -0.29148248,  0.7500035 ]],
      dtype=float32)

In [20]:
tf.nn.softmax(predictions).numpy()

array([[0.08726969, 0.15488265, 0.04169194, 0.09774798, 0.15631078,
        0.08977014, 0.06546794, 0.0588223 , 0.06470367, 0.18333296]],
      dtype=float32)

In [21]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [22]:
loss_fn(y_train[:1], predictions).numpy()

2.410503

In [28]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [29]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 7s 113us/sample - loss: 0.2897 - accuracy: 0.9155
Epoch 2/5
60000/60000 [==============================] - 6s 93us/sample - loss: 0.1408 - accuracy: 0.9576
Epoch 3/5
60000/60000 [==============================] - 6s 102us/sample - loss: 0.1048 - accuracy: 0.9678
Epoch 4/5
60000/60000 [==============================] - 6s 106us/sample - loss: 0.0855 - accuracy: 0.9739
Epoch 5/5
60000/60000 [==============================] - 6s 95us/sample - loss: 0.0758 - accuracy: 0.9761


In [31]:
model.evaluate(x_test,  y_test, verbose=2)

10000/10000 - 0s - loss: 0.0763 - accuracy: 0.9767


[0.0762533833861351, 0.9767]

In [32]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [26]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.07103918, 0.12568088, 0.07621099, 0.11799533, 0.10423192,
        0.12802623, 0.05449665, 0.10860567, 0.06689947, 0.14681375],
       [0.05974109, 0.19087437, 0.03894789, 0.08174793, 0.05884857,
        0.11966047, 0.08241608, 0.12291545, 0.08066855, 0.16417955],
       [0.09766749, 0.08399333, 0.10542266, 0.10672806, 0.10677619,
        0.07971023, 0.06568503, 0.10884141, 0.11915106, 0.12602447],
       [0.06211234, 0.25425032, 0.03914524, 0.06677743, 0.09316883,
        0.10621448, 0.02883818, 0.08496175, 0.03038369, 0.23414776],
       [0.09587356, 0.24778059, 0.07180673, 0.09271751, 0.0835283 ,
        0.09836957, 0.05798249, 0.12664346, 0.05775492, 0.0675429 ]],
      dtype=float32)>

In [3]:
name = "Akahs"
age = 23

In [4]:
print("My name is {} and my age in {}".format(name,age))

My name is Akahs and my age in 23


In [5]:
print("My name is {} and my age is {}".format(name,age))

My name is Akahs and my age is 23


In [6]:
{1,1,1,2,2,2,3,3,3}

{1, 2, 3}

In [7]:
{1,2,3,4,5,6,7,8}

{1, 2, 3, 4, 5, 6, 7, 8}

In [11]:
i = 1
while i<5:
    print("i is: {}".format(i))
    i = i+1

i is: 1
i is: 2
i is: 3
i is: 4


In [27]:
x= [1,2,3,4]

In [28]:
out = []
for num in x:
    out.append(num**2)

In [29]:
print(out)

[1, 4, 9, 16]


In [30]:
[num ** 2 for num in x]

[1, 4, 9, 16]

In [33]:
out = [num ** 2 for num in x]

In [34]:
out

[1, 4, 9, 16]

In [44]:
def my_func(param1 = "Akash"):
    print("Hello "+param1)

In [46]:
my_func("Maruf")

Hello Maruf


In [47]:
my_func

<function __main__.my_func(param1='Akash')>

In [51]:
def square(num):
    """This is a DocSTRing"""
    return num**2

In [52]:
output = square(2)

In [53]:
output

4

In [58]:
def times2(var):
    return var*2

In [59]:
times2(5)

10

In [60]:
seq = [1,2,3,4,5]

In [62]:
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [63]:
def times2(var):return var*2

In [65]:
times2(5)

10

In [10]:
t= lambda var:var*2

In [11]:
t(5)

10

In [69]:
seq = [1,2,3,4,5]
list(map(lambda num: num*3,seq))

[3, 6, 9, 12, 15]

In [12]:
word_list = 'Hello World'
later_list= []
for a_word in word_list:
    for a_later in a_word:
        later_list.append(a_later)
print(later_list)        

['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd']


In [70]:
list(map(lambda num: num*3, seq))

[3, 6, 9, 12, 15]

In [3]:
my=[1,2,4,5,6]
my[2:5]

[4, 5, 6]