In [4]:
print("Hello World")

In [ ]:
import numpy as np

In [2]:
np.random.randint(2,10,20)

array([6, 3, 4, 9, 6, 6, 4, 4, 4, 7, 7, 3, 3, 2, 6, 9, 7, 9, 5, 9])

In [3]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.random.randn(10)

array([ 0.03689688,  3.15263492,  1.79029563,  1.19644477,  0.55837536,
        0.25775698,  1.47285049, -0.26510934,  0.28534405, -0.63524536])

In [6]:
np.random.rand(5)

array([0.15507719, 0.71623828, 0.45402332, 0.472856  , 0.01364861])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.random.randint(0,10,10)

array([3, 1, 1, 4, 8, 6, 3, 0, 2, 7])

In [6]:
np.eye(5,4)*5

array([[5., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 5., 0.],
       [0., 0., 0., 5.],
       [0., 0., 0., 0.]])

In [3]:
np.zeros((5,2))+10

array([[10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.]])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.ones((10,9)) * 5

array([[5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [13]:
my_list = [1,2,3,4,5,6,7]

In [14]:
arrayToList = np.array(my_list)

In [15]:
arrayToList

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
array_list = np.arange(5,12)

In [23]:
array_list

array([ 5,  6,  7,  8,  9, 10, 11])

In [22]:
x = arrayToList + array_list

In [24]:
print(x)

[ 6  8 10 12 14 16 18]


In [25]:
x[0:5]

array([ 6,  8, 10, 12, 14])

In [26]:
x[:]

array([ 6,  8, 10, 12, 14, 16, 18])

In [27]:
x[:] = 10

In [28]:
x

array([10, 10, 10, 10, 10, 10, 10])

In [30]:
x

array([10, 10, 10, 10, 10, 10, 10])

In [34]:
x = np.random.randint(0,10,5)

In [36]:
y = np.arange(0,5)

In [37]:
x+y

array([9, 1, 9, 6, 6])

In [38]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.eye(5)*4

array([[4., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [0., 0., 4., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 4.]])

In [41]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [47]:
np.zeros((5,2)) + 10

array([[10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.],
       [10., 10.]])

In [48]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
my_list = [3,54,65,6,767,6]

In [61]:
x =np.array(my_list)

In [62]:
np.shape(my_list)

(6,)

In [63]:
x.reshape(3,2)

array([[  3,  54],
       [ 65,   6],
       [767,   6]])

In [64]:
x.shape

(6,)

In [65]:
x.dtype

dtype('int32')

In [66]:
x.max()

767

In [67]:
x.min()

3

In [68]:
x.argmin()

0

In [69]:
x.argmax()

4

In [70]:
my_array_list = [[2,3,4],[5,6,7],[7,8,9],]

In [79]:
x = np.array(my_array_list)

In [77]:
my_array_list[2][2]

9

In [81]:
x.reshape(3,3)

array([[2, 3, 4],
       [5, 6, 7],
       [7, 8, 9]])